app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__, template_folder="templates")

from app.main import routes

app/main/routes.py
from flask import redirect, render_template, request, url_for, flash, current_app, send_from_directory
from flask_login import login_required, login_user, logout_user, current_user
from werkzeug.security import generate_password_hash, check_password_hash
from app.main import bp
from app.extensions import db
from app.main.user import User
from app.projects.task import Task
from app.projects.project import Project
from app.projects.event import Event
from datetime import datetime, timedelta
import os

@bp.route('/tasks')
@login_required
def tasks():
    tasks = Task.query.all()
    return render_template('tasks-all.html', tasks=tasks)
@bp.route('/tasks/today')
@login_required
def tasks_today():
    tasks = Task.query.filter_by(due_date = datetime.today().strftime('%Y-%m-%d'))
    return render_template('tasks-today.html', tasks=tasks)
@bp.route('/events')
@login_required
def events():
    #id = 1 #TO DO
    projects = Project.query.all()
    #project = Project.query.filter_by(id = id).first_or_404()
    return render_template('events.html', projects=projects)
@bp.route('/day-plan', methods=['GET', 'POST'])
@login_required
def day_plan():
    selected_date = datetime.today().strftime('%Y-%m-%d')
    selected_date_start = datetime.today().strftime('%Y-%m-%d 00:00:00')
    selected_date_end = datetime.today().strftime('%Y-%m-%d 23:59:59')
    if request.method == 'POST':
        selected_date = request.form.get('date')
        selected_date_start = selected_date + " 00:00:00"
        selected_date_end = selected_date + "23:59:59"
    daily_events = Event.query.filter(Event.start >= selected_date_start, Event.end <= selected_date_end).order_by(Event.start)
    for event in daily_events:
        if not event.all_day:
            event.travel_start = event.start - timedelta(minutes=event.travel_time or 0)
    return render_template('day-plan.html', events = daily_events, date = selected_date)
@bp.route('/', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        user = User.query.filter_by(username=username).first()

        if user and check_password_hash(user.password, password):
            print("test")
            login_user(user)
            return redirect(url_for('projects.index'))

        flash('Invalid username or password.', category="warning")
        print("Invalid username or password")
        return redirect(url_for('main.register'))
    return render_template('login.html')

@bp.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST' and int(current_app.config.get('REGISTER')) == 1:
        if request.form["password"] == request.form["confirm-password"]:
            existing_user = User.query.filter_by(username=request.form["username"]).first()
            if existing_user is None:
                username = request.form.get('username')
                password = request.form.get('password')
                hashed_password = generate_password_hash(password, method='pbkdf2:sha256')
                new_user = User(username=username, password=hashed_password)
                db.session.add(new_user)
                db.session.commit()
                flash("Registered successfully. You can login now.", category="success")
            else:
                flash('Username already taken, please choose another one.', 'warning')
                return redirect(url_for('main.register'))

        else:
            flash("Passwords don't match.", category="warning")
            return redirect(url_for('main.register'))

        return redirect(url_for('main.login'))
    return render_template('register.html')
@bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.login'))
@bp.route('/edit-profile', methods=["GET", "POST"])
@login_required
def edit_profile():
    if request.method == "POST":
        existing_user = User.query.filter_by(username = request.form["username"]).first()
        if existing_user is None or existing_user.username == current_user.username:     
            if request.form["password"] == request.form["confirm-password"] and request.form["password"] != "":
                current_user.username = request.form["username"]
                current_user.password = generate_password_hash(request.form["password"], method='pbkdf2:sha256')
                db.session.commit()
                flash("Username and password updated successfully.", category="success")
            elif request.form["password"] == "":
                current_user.username = request.form["username"]
                db.session.commit()
                flash("Username updated successfully.", category="success")
            else:
                flash("Passwords don't match!", category="warning")
        else:
            flash("Username already taken.", category="warning")
    return render_template('edit-profile.html')

app/main/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Project management app</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.15.3/dist/katex.min.css">


    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">

    {% block head_files %}{% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark">
        {% block navbar_title %}{% endblock %}

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item mx-2">
                    <a class="nav-link" href="{{ url_for('projects.index') }}"><i class="fas fa-calendar-alt"></i> Projects</a>
                </li>
                <li class="nav-item mx-2">
                    <a class="nav-link" href="{{ url_for('main.events') }}"><i class="fas fa-calendar-alt"></i> Calendar</a>
                </li>
                <li class="nav-item mx-2">
                    <a class="nav-link" href="{{ url_for('main.tasks') }}"><i class="fas fa-tasks"></i> Tasks</a>
                </li>
                {% if current_user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="userMenu" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <img src="https://via.placeholder.com/30" alt="Avatar" class="avatar">
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                        <a class="dropdown-item" href="#">{{ current_user.username }}</a>
                        <a class="dropdown-item" href="{{ url_for('main.edit_profile') }}">Edit profile</a>
                        <a class="dropdown-item" href="{{ url_for('main.logout') }}">Logout</a>
                    </div>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <!-- <div class="alert alert-{{ category }}">{{ message }}</div> -->
            {% endfor %}
        {% endif %}
    {% endwith %}
  
    {% block content %}{% endblock %}

    <!-- <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script> -->
    <!-- <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script> -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/katex@0.15.3/dist/katex.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/katex/dist/contrib/auto-render.min.js"></script>


    

    {% block javascript %}{% endblock %}

    {% block js_files %} {% endblock %}
</body>
</html>

app/main/templates/day-plan.html
{% extends 'base.html' %}

{% block head_files %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fullcalendar@6.1.8/main.min.css">
{% endblock %}

{% block navbar_title %}
    <a class="navbar-brand" href="#">All events</a>
{% endblock %}

{% block content %}
   
   <div class="sidebar">
        <ul class="nav nav-pills flex-column mb-auto">
            <li class="nav-item">
                <a href="{{ url_for('main.day_plan') }}" class="nav-link active">
                    <i class="fas fa-info"></i>
                    Day dashboard
                </a>
            </li>
            <li class="nav-item">
                <a href="{{ url_for('main.events') }}" class="nav-link">
                    <i class="fas fa-tasks"></i>
                    Calendar
                </a>
            </li>            
          </ul>
    </div>
    <div class="content">
      <form method="POST">
          <label for="date">Wybierz datę:</label>
          <input type="date" id="date" name="date" value="{{ date }}" required>
          <button id="submit" style="display: none;" type="submit">Pokaż wydarzenia</button>
      </form>
        {{ date }}
        <ul>
            {% for event in events %}
              {% if event.all_day == 1 %}
                {% if event.travel_time or event.location %} <li><i>{{ event.travel_time }} (travel), location: {{ event.location }}</i></li> {% endif %}
              {% else %}
                {% if event.travel_time or event.location %} <li>{{ event.travel_start.strftime("%H:%M") }} <i>(travel), location: {{ event.location }}</i></li> {% endif %}
              {% endif %}
              <li>{% if event.all_day == 0 %} {{ event.start.strftime("%H:%M") }} - {{ event.end.strftime("%H:%M") }} {% endif %}<b>{{ event.name }}</b></li>
            {% endfor %}
        </ul>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="eventModal" tabindex="-1" aria-labelledby="eventModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="eventModalLabel">Event Details</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <p id="project-name"></p>
            <form id="eventForm">
              <div class="mb-3">
                <label for="eventTitle" class="form-label">Event Title</label>
                <input type="text" class="form-control" id="eventTitle">
              </div>
              <div class="mb-3">
                <label for="eventStart" class="form-label">Start Date</label>
                <input type="datetime-local" class="form-control" id="eventStart">
              </div>
              <div class="mb-3">
                <label for="eventEnd" class="form-label">End Date</label>
                <input type="datetime-local" class="form-control" id="eventEnd">
              </div>
            </form>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-danger" id="deleteEvent">Delete</button>
            <button type="button" class="btn btn-primary" id="saveEvent">Save</button>
          </div>
        </div>
      </div>
    </div>
{% endblock %}
    
{% block javascript %}
{% endblock %}

{% block js_files %}
<script src="{{ url_for('static', filename='js/day-plan.js') }}"></script>
{% endblock %}

app/main/templates/edit-profile.html
{% extends "base.html" %}

{% block content %}

<div class="content">
    <div class="card" style="width: 400px;">
        <div class="card-body bg-dark text-light">
            <h3 class="text-center">Edit profile</h3>
            <form method="POST" action="{{ url_for('main.edit_profile') }}">
                <div class="mb-3">
                    <label for="username" class="form-label">Username</label>
                    <input type="text" class="form-control" id="username" name="username" value="{{ current_user.username }}" required>
                </div>
                <div class="mb-3">
                    <label for="password" class="form-label">Password</label>
                    <input type="password" class="form-control" id="password" name="password">
                </div>
                <div class="mb-3">
                    <label for="confirm-password" class="form-label">Confirm password</label>
                    <input type="password" class="form-control" id="confirm-password" name="confirm-password">
                </div>
                <button type="submit" class="btn btn-custom w-100">Save</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

app/main/templates/events.html
{% extends 'base.html' %}

{% block head_files %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fullcalendar@6.1.8/main.min.css">
{% endblock %}

{% block navbar_title %}
    <a class="navbar-brand" href="#">All events</a>
{% endblock %}

{% block content %}
   
   <div class="sidebar">
        <ul class="nav nav-pills flex-column mb-auto">
            <li class="nav-item">
                <a href="#" class="nav-link">
                    <i class="fas fa-info"></i>
                    Day dashboard
                </a>
            </li>
            <li class="nav-item">
                <a href="{{ url_for('main.events') }}" class="nav-link active">
                    <i class="fas fa-tasks"></i>
                    Calendar
                </a>
            </li>            
          </ul>
    </div>
    <div class="content">
        <div id="calendar"></div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="eventModal" tabindex="-1" aria-labelledby="eventModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="eventModalLabel">Event Details</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <p id="project-name"></p>
            <form id="eventForm">
              <div class="mb-3">
                <label for="eventTitle" class="form-label">Event Title</label>
                <input type="text" class="form-control" id="eventTitle">
              </div>
              <div class="mb-3">
                <label for="eventStart" class="form-label">Start Date</label>
                <input type="datetime-local" class="form-control" id="eventStart">
              </div>
              <div class="mb-3">
                <label for="eventEnd" class="form-label">End Date</label>
                <input type="datetime-local" class="form-control" id="eventEnd">
              </div>
            </form>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-danger" id="deleteEvent">Delete</button>
            <button type="button" class="btn btn-primary" id="saveEvent">Save</button>
          </div>
        </div>
      </div>
    </div>
{% endblock %}
    
{% block javascript %}
<script src='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.15/index.global.min.js'></script>
{% endblock %}

{% block js_files %}
<script src="{{ url_for('static', filename='js/calendar.js') }}"></script>
<script src="{{ url_for('static', filename='js/project-edit-name.js') }}"></script>
<script src="{{ url_for('static', filename='js/project-tasks.js') }}"></script>
{% endblock %}

app/main/templates/index.html
{% extends "base.html" %}

{% block content %}

<div class="content">
    <div class="card bg-dark text-light">
        <div class="card-body">
          <h5 class="card-title">Welcome!</h5>
          <p class="card-text">(Login)</p>
          <a href="{{ url_for('projects.index') }}" class="btn btn-primary">Go to app</a>
        </div>
      </div>
</div>

{% endblock %}

app/main/templates/login.html
{% extends "base.html" %}

{% block content %}

<div class="content">
  <div class="card" style="width: 400px;">
    <div class="card-body bg-dark text-light" >
        <h3 class="text-center">Login</h3>
        <form method="POST" action="{{ url_for('main.login') }}">
            <div class="mb-3">
                <label for="username" class="form-label">Username</label>
                <input type="text" class="form-control" id="username" name="username" required>
            </div>
            <div class="mb-3">
                <label for="password" class="form-label">Password</label>
                <input type="password" class="form-control" id="password" name="password" required>
            </div>
            <button type="submit" class="btn btn-custom w-100">Login</button>
        </form>
        <div class="mt-3 text-center">
            <a href="{{ url_for('main.register') }}">Don't have an account? Register</a>
        </div>
    </div>
</div>
</div>

{% endblock %}

app/main/templates/register.html
{% extends "base.html" %}

{% block content %}

<div class="content">
    <div class="card" style="width: 400px;">
        <div class="card-body bg-dark text-light">
            <h3 class="text-center">Register</h3>
            <form method="POST" action="{{ url_for('main.register') }}">
                <div class="mb-3">
                    <label for="username" class="form-label">Username</label>
                    <input type="text" class="form-control" id="username" name="username" required>
                </div>
                <div class="mb-3">
                    <label for="password" class="form-label">Password</label>
                    <input type="password" class="form-control" id="password" name="password" required>
                </div>
                <div class="mb-3">
                    <label for="confirm-password" class="form-label">Confirm password</label>
                    <input type="password" class="form-control" id="confirm-password" name="confirm-password" required>
                </div>
                <button type="submit" class="btn btn-custom w-100">Register</button>
            </form>
            <div class="mt-3 text-center">
                <a href="{{ url_for('main.login') }}">Already have an account? Login</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

app/main/templates/tasks-all.html
{% extends 'base.html' %}

{% block navbar_title %}
    <a class="navbar-brand" href="#">All tasks</a>
{% endblock %}

{% block content %}
   
   <div class="sidebar">
        <ul class="nav nav-pills flex-column mb-auto">
            <li class="nav-item">
                <a href="{{ url_for('main.tasks_today') }}" class="nav-link">
                    <i class="fas fa-info"></i>
                    Today
                </a>
            </li>
            <li class="nav-item">
                <a href="{{ url_for('main.tasks') }}" class="nav-link active">
                    <i class="fas fa-tasks"></i>
                    All
                </a>
            </li>
            
          </ul>
    </div>
    <div class="content">
        <!-- Task List Section -->
        <div class="task-list">
            {% for task in tasks %}
            <div class="task-item" data-id="{{ task.id }}" data-name="{{ task.name }}">
                <span contenteditable="true" class="task-name">{{ task.name }}</span>
                <div class="task-date">
                    <a href="#" class="star-task" data-id="{{ task.id }}">{% if task.starred == 1 %} Starred {% else %} Star {% endif %}</a>
                    <input type="date" class="task-change-date" value="{{ task.due_date }}">
                    <button type="button" class="btn btn-outline-danger btn-sm delete-task">Delete</button>
                </div>
                
            </div>
            {% endfor %}
        </div>

    </div>

{% endblock %}
    
{% block javascript %}
<script>
    const project_id = "1";
</script>
{% endblock %}

{% block js_files %}
<script src="{{ url_for('static', filename='js/project-tasks.js') }}"></script>
{% endblock %}

app/main/templates/tasks-today.html
{% extends 'base.html' %}

{% block navbar_title %}
    <a class="navbar-brand" href="#">All tasks</a>
{% endblock %}

{% block content %}
   
   <div class="sidebar">
        <ul class="nav nav-pills flex-column mb-auto">
            <li class="nav-item">
                <a href="{{ url_for('main.tasks_today') }}" class="nav-link active">
                    <i class="fas fa-info"></i>
                    Today
                </a>
            </li>
            <li class="nav-item">
                <a href="{{ url_for('main.tasks') }}" class="nav-link">
                    <i class="fas fa-tasks"></i>
                    All
                </a>
            </li>
            
          </ul>
    </div>
    <div class="content">
        <!-- Task List Section -->
        <div class="task-list">
            {% for task in tasks %}
            <div class="task-item" data-id="{{ task.id }}" data-name="{{ task.name }}">
                <span contenteditable="true" class="task-name">{{ task.name }}</span>
                <div class="task-date">
                    <input type="date" class="task-change-date" value="{{ task.due_date }}">
                    <button type="button" class="btn btn-outline-danger btn-sm delete-task">Delete</button>
                </div>
                
            </div>
            {% endfor %}
        </div>

    </div>

{% endblock %}
    
{% block javascript %}
<script>
    const project_id = "1";
</script>
{% endblock %}

{% block js_files %}
<script src="{{ url_for('static', filename='js/project-edit-name.js') }}"></script>
<script src="{{ url_for('static', filename='js/project-tasks.js') }}"></script>
{% endblock %}